resolver: lts-11.7
packages:
  - '.'

extra-deps:
- git: https://github.com/f-o-a-m/purescript-bridge.git
  commit: 2a2c8e34f580b7ec23dd6ef75a07439636bdbbc5 #better-generics
- servant-foreign-0.11.1

flags: {}
 
extra-package-dbs: []

nix:
   shell-file: stack-8.0.nix
