-- File auto generated by purescript-bridge! --
module ServerTypes where

import Data.Lens (Iso', Lens', Prism', lens, prism')
import Data.Lens.Iso.Newtype (_Newtype)
import Data.Lens.Record (prop)
import Data.Maybe (Maybe(..))
import Data.Newtype (class Newtype)
import Data.Symbol (SProxy(SProxy))
import Prim (String)

import Prelude
import Data.Generic (class Generic)

newtype Hello =
    Hello {
      message :: String
    }

derive instance genericHello :: Generic Hello

derive instance newtypeHello :: Newtype Hello _


--------------------------------------------------------------------------------
_Hello :: Iso' Hello { message :: String}
_Hello = _Newtype

--------------------------------------------------------------------------------
newtype TestHeader =
    TestHeader String

derive instance genericTestHeader :: Generic TestHeader

derive instance newtypeTestHeader :: Newtype TestHeader _


--------------------------------------------------------------------------------
_TestHeader :: Iso' TestHeader String
_TestHeader = _Newtype
--------------------------------------------------------------------------------
